apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-front-depl
spec:
  selector:
    matchLabels:
      app: react-front
  replicas: 1 
  template:
    metadata:
      labels:
        app: react-front
    spec:
      containers:
        - name: react-frontend
          image: realestate1234/react-frontend
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          
---

apiVersion: v1
kind: Service
metadata:
  name: react-frontend-svc
spec:
  type: NodePort
  selector:
    app: react-front
  ports:
  - port: 3001
    targetPort: 5173

